package mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pojo.Aircraft;
import pojo.AircraftExample;

public interface AircraftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircraft
     *
     * @mbg.generated
     */
    long countByExample(AircraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircraft
     *
     * @mbg.generated
     */
    int deleteByExample(AircraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircraft
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircraft
     *
     * @mbg.generated
     */
    int insert(Aircraft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircraft
     *
     * @mbg.generated
     */
    int insertSelective(Aircraft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircraft
     *
     * @mbg.generated
     */
    List<Aircraft> selectByExample(AircraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircraft
     *
     * @mbg.generated
     */
    Aircraft selectByPrimaryKey(String aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircraft
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Aircraft record, @Param("example") AircraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircraft
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Aircraft record, @Param("example") AircraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircraft
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Aircraft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aircraft
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Aircraft record);
}