package mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pojo.Flight;
import pojo.FlightExample;
import system.Page;

public interface FlightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbg.generated
     */
    long countByExample(FlightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbg.generated
     */
    int deleteByExample(FlightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer fId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbg.generated
     */
    int insert(Flight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbg.generated
     */
    int insertSelective(Flight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbg.generated
     */
    List<Flight> selectByExample(FlightExample example);
    List<Flight> selectByExample(FlightExample example,Page page);
   
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbg.generated
     */
    Flight selectByPrimaryKey(Integer fId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Flight record, @Param("example") FlightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Flight record, @Param("example") FlightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Flight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Flight record);
}