package pojo;

public class Aircraft {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aircraft.a_id
     *
     * @mbg.generated
     */
    private String aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aircraft.company
     *
     * @mbg.generated
     */
    private String company;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aircraft.a_id
     *
     * @return the value of aircraft.a_id
     *
     * @mbg.generated
     */
    public String getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aircraft.a_id
     *
     * @param aId the value for aircraft.a_id
     *
     * @mbg.generated
     */
    public void setaId(String aId) {
        this.aId = aId == null ? null : aId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aircraft.company
     *
     * @return the value of aircraft.company
     *
     * @mbg.generated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aircraft.company
     *
     * @param company the value for aircraft.company
     *
     * @mbg.generated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }
}