package pojo;

import java.util.Date;

public class Flight {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.f_id
     *
     * @mbg.generated
     */
    private Integer fId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.a_id
     *
     * @mbg.generated
     */
    private String aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.departure_time
     *
     * @mbg.generated
     */
    private Date departureTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.arrival_time
     *
     * @mbg.generated
     */
    private Date arrivalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.departure_place
     *
     * @mbg.generated
     */
    private String departurePlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.arrival_place
     *
     * @mbg.generated
     */
    private String arrivalPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.fristclass_price
     *
     * @mbg.generated
     */
    private Integer fristclassPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.economy_count
     *
     * @mbg.generated
     */
    private Integer economyCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.economy_price
     *
     * @mbg.generated
     */
    private Integer economyPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.fristclass_count
     *
     * @mbg.generated
     */
    private Integer fristclassCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.f_id
     *
     * @return the value of flight.f_id
     *
     * @mbg.generated
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.f_id
     *
     * @param fId the value for flight.f_id
     *
     * @mbg.generated
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.a_id
     *
     * @return the value of flight.a_id
     *
     * @mbg.generated
     */
    public String getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.a_id
     *
     * @param aId the value for flight.a_id
     *
     * @mbg.generated
     */
    public void setaId(String aId) {
        this.aId = aId == null ? null : aId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.departure_time
     *
     * @return the value of flight.departure_time
     *
     * @mbg.generated
     */
    public Date getDepartureTime() {
        return departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.departure_time
     *
     * @param departureTime the value for flight.departure_time
     *
     * @mbg.generated
     */
    public void setDepartureTime(Date departureTime) {
        this.departureTime = departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.arrival_time
     *
     * @return the value of flight.arrival_time
     *
     * @mbg.generated
     */
    public Date getArrivalTime() {
        return arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.arrival_time
     *
     * @param arrivalTime the value for flight.arrival_time
     *
     * @mbg.generated
     */
    public void setArrivalTime(Date arrivalTime) {
        this.arrivalTime = arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.departure_place
     *
     * @return the value of flight.departure_place
     *
     * @mbg.generated
     */
    public String getDeparturePlace() {
        return departurePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.departure_place
     *
     * @param departurePlace the value for flight.departure_place
     *
     * @mbg.generated
     */
    public void setDeparturePlace(String departurePlace) {
        this.departurePlace = departurePlace == null ? null : departurePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.arrival_place
     *
     * @return the value of flight.arrival_place
     *
     * @mbg.generated
     */
    public String getArrivalPlace() {
        return arrivalPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.arrival_place
     *
     * @param arrivalPlace the value for flight.arrival_place
     *
     * @mbg.generated
     */
    public void setArrivalPlace(String arrivalPlace) {
        this.arrivalPlace = arrivalPlace == null ? null : arrivalPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.fristclass_price
     *
     * @return the value of flight.fristclass_price
     *
     * @mbg.generated
     */
    public Integer getFristclassPrice() {
        return fristclassPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.fristclass_price
     *
     * @param fristclassPrice the value for flight.fristclass_price
     *
     * @mbg.generated
     */
    public void setFristclassPrice(Integer fristclassPrice) {
        this.fristclassPrice = fristclassPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.economy_count
     *
     * @return the value of flight.economy_count
     *
     * @mbg.generated
     */
    public Integer getEconomyCount() {
        return economyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.economy_count
     *
     * @param economyCount the value for flight.economy_count
     *
     * @mbg.generated
     */
    public void setEconomyCount(Integer economyCount) {
        this.economyCount = economyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.economy_price
     *
     * @return the value of flight.economy_price
     *
     * @mbg.generated
     */
    public Integer getEconomyPrice() {
        return economyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.economy_price
     *
     * @param economyPrice the value for flight.economy_price
     *
     * @mbg.generated
     */
    public void setEconomyPrice(Integer economyPrice) {
        this.economyPrice = economyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.fristclass_count
     *
     * @return the value of flight.fristclass_count
     *
     * @mbg.generated
     */
    public Integer getFristclassCount() {
        return fristclassCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.fristclass_count
     *
     * @param fristclassCount the value for flight.fristclass_count
     *
     * @mbg.generated
     */
    public void setFristclassCount(Integer fristclassCount) {
        this.fristclassCount = fristclassCount;
    }
}