package pojo;

import java.util.Date;

public class Passenger {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.phone
     *
     * @mbg.generated
     */
    private Integer phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.p_name
     *
     * @mbg.generated
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.p_id
     *
     * @mbg.generated
     */
    private String pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.brithday
     *
     * @mbg.generated
     */
    private Date brithday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.phone
     *
     * @return the value of passenger.phone
     *
     * @mbg.generated
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.phone
     *
     * @param phone the value for passenger.phone
     *
     * @mbg.generated
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.p_name
     *
     * @return the value of passenger.p_name
     *
     * @mbg.generated
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.p_name
     *
     * @param pName the value for passenger.p_name
     *
     * @mbg.generated
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.p_id
     *
     * @return the value of passenger.p_id
     *
     * @mbg.generated
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.p_id
     *
     * @param pId the value for passenger.p_id
     *
     * @mbg.generated
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.sex
     *
     * @return the value of passenger.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.sex
     *
     * @param sex the value for passenger.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.brithday
     *
     * @return the value of passenger.brithday
     *
     * @mbg.generated
     */
    public Date getBrithday() {
        return brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.brithday
     *
     * @param brithday the value for passenger.brithday
     *
     * @mbg.generated
     */
    public void setBrithday(Date brithday) {
        this.brithday = brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.password
     *
     * @return the value of passenger.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.password
     *
     * @param password the value for passenger.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.city
     *
     * @return the value of passenger.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.city
     *
     * @param city the value for passenger.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.email
     *
     * @return the value of passenger.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.email
     *
     * @param email the value for passenger.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}